In [20]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Load dataset
iris = load_iris()
X = iris.data
y = iris.target

print("Dataset used: IRIS")
print("Feature names:", iris.feature_names)
print("Target classes:", iris.target_names)

# Split dataset (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train Decision Tree using entropy (ID3 logic)
model = DecisionTreeClassifier(criterion="entropy", random_state=42)
model.fit(X_train, y_train)

# Predictions on test set
y_pred = model.predict(X_test)

# ===== METRICS =====
print("\nModel Evaluation Metrics")
print("-------------------------")

# Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Precision, Recall, F1-score
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))

# New sample prediction
sample = [[3.1, 8.5, 5.4, 7.2]]
prediction = model.predict(sample)
print("\nPredicted class for new sample:",
      iris.target_names[prediction][0])

Dataset used: IRIS
Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target classes: ['setosa' 'versicolor' 'virginica']

Model Evaluation Metrics
-------------------------
Accuracy: 1.0

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30


Predicted class for new sample: virginica


In [18]:
from sklearn.datasets import load_diabetes
from sklearn.tree import DecisionTreeRegressor

from sklearn.datasets import load_diabetes
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

# Load dataset
data = load_diabetes()
X = data.data
y = data.target

print("Dataset used: DIABETES")
print("Number of features:", X.shape[1])

# Split dataset (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train regression tree
model = DecisionTreeRegressor(random_state=42)
model.fit(X_train, y_train)

# Predictions on test set
y_pred = model.predict(X_test)

# ===== METRICS =====
print("\nModel Evaluation Metrics")
print("-------------------------")

# Mean Absolute Error (MAE)
print("MAE:", mean_absolute_error(y_test, y_pred))

# Mean Squared Error (MSE)
print("MSE:", mean_squared_error(y_test, y_pred))

# Root Mean Squared Error (RMSE)
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

# R² Score
print("R2 Score:", r2_score(y_test, y_pred))

# New sample prediction
sample = [X[0]]
prediction = model.predict(sample)
print("\nPredicted disease progression:", prediction[0])

Dataset used: DIABETES
Number of features: 10

Model Evaluation Metrics
-------------------------
MAE: 54.52808988764045
MSE: 4976.797752808989
RMSE: 70.54642267903446
R2 Score: 0.060653981041140725

Predicted disease progression: 198.0
